version: "3.7"
services:
  v2lbsyun.local:
    hostname: v2lbsyun.local
    image: xianheyan/v2lbsyun:v0.0.8
    container_name: v2lbsyun
    environment:
      - TZ=Asia/Shanghai
      - EXTERNAL_URL=http://192.168.31.202:8000
      - API_WEBGL=https://api.map.baidu.com/api?v=1.0&type=webgl&ak=
      - REDIS_PWD=redis1
    ports:
      - "8000:8000"
  redis.local:
    hostname: redis.local
    image: redis:6.2.6
    restart: always
    command: redis-server --requirepass redis1 --save "" --maxmemory 5gb --timeout 0 --tcp-keepalive 60 --bind 0.0.0.0
    environment:
      - TZ=Asia/Shanghai
